name: Scheduled Health Check

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  health_check_job:
    runs-on: self-hosted
    name: Check all sites
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Shell Script
        id: shell_script_run
        run: bash ./health-check.sh
